### ISSUE TITLE
MachineLearning_Toolkit: Wrong warning message when run installMachineLearningToolkit for the first time

### ISSUE THREAD

**Issue by BingWangUS** [BHoM/MachineLearning_Toolkit#21]
#### Description:

I did a installation with the following steps:
 1. Install daily alpha
 2. Compile Python_toolkit from master
 3. Compile MachineLearning_toolkit from master
 4. Use InstallPythonToolkit component
 5. Use InstallMachineLearningToolkit component

During the step 5, it takes 3-4s to load the component. After loading, with nothing is connected to the run toggle (default as false), it is giving the following warning message. (PS These warning message are from the Private Fields of Invoke.cs from MachineLearning_Toolkit.)
![image](https://user-images.githubusercontent.com/10835375/87560937-fd41f980-c689-11ea-8e12-4276651a6013.png)
1. ModuleNotFoundError : No module named 'MachineLearning_Engine'
1. ModuleNotFoundError : No module named 'numpy'

However, The warning message will not be there if we create a new InstallMachineLearning component (without running the previous InstallMachineLearning component). But if we closed Rhino and reopen Grasshopper, it will happen again. So the warning message is only happening when the first time InstallMachineLearning is loaded, and only happen once. 

This seems to me going to the opposite side we want the warning message - it should not warn the the first time because it is of course not there before installation. And thinking about it, it seems unnecessary to have a checking for InstallMachineLearning component.

**Comment by BingWangUS** [comment]
After looking at the code, I cannot figure it out what is making it different when loading the component for the first time. Feels like this is a UI question so tagging @adecler for some insights.

**Comment by epignatelli** [comment]
I don't think that's the case, this is a toolkit-specific issue.

The `static` fields are initialised even if nothing is called, and they call the `Import` method. Since they lie in the `Compute` class, which is also where the `InstallMachineLearningToolkit` method resides, you get the warning.

We can distinguish the cases when the toolkit is already installed
This requires a method to check if the toolkit is installed, which is not available yet - that's why the bug. 

That may be annoying, I agree, but I haven't had the time to code that yet, feel free to give it a go!

**Comment by BingWangUS** [comment]
> I don't think that's the case, this is a toolkit-specific issue.
> 
> The `static` fields are initialised even if nothing is called, and they call the `Import` method. Since they lie in the `Compute` class, which is also where the `InstallMachineLearningToolkit` method resides, you get the warning.
> 
> We can distinguish the cases when the toolkit is already installed
> This requires a method to check if the toolkit is installed, which is not available yet - that's why the bug.
> 
> That may be annoying, I agree, but I haven't had the time to code that yet, feel free to give it a go!

Thanks. This make sense. Creating a new issue to capture the checking feature request.
