### ISSUE TITLE
MachineLearning_Toolkit: Checking if python toolkit and machinelearning toolkit is installed for InstallMachineLearning component

### ISSUE THREAD

**Issue by BingWangUS** [BHoM/MachineLearning_Toolkit#22]
#### Description:

As title, a feature to check if the python toolkit and machinelearning toolkit are installed successfully is needed for the InstallMachineLearning component. We may considering calling InstallPythonToolkit if checking is failed. 

This feature is also related to #21

**Comment by FraserGreenroyd** [comment]
Have you tried the `IsInstalled` component from each toolkit?

**Comment by FraserGreenroyd** [comment]
Ok just double checked, it exists for Python TK already as `IsPythonInstalled` but not for this toolkit so I guess feature is for this toolkit only? :smile:
