### ISSUE TITLE
Add PlotRose method

### ISSUE THREAD

**Issue by tg359** [BHoM/MachineLearning_Toolkit#41]
#### Description:

Include a method to generate a rose plot from wind-directions and variables.

**Comment by tg359** [comment]
@epignatelli Here's a test script to run against this branch which is currently throwing an error - see screenshots below:

![image](https://user-images.githubusercontent.com/10939984/88948833-53b65700-d28a-11ea-8d85-d565d516dc1c.png)
![image](https://user-images.githubusercontent.com/10939984/88948906-6df03500-d28a-11ea-8655-a59288205bc7.png)

[example.zip](https://github.com/BHoM/MachineLearning_Toolkit/files/5002560/example.zip)

**Comment by epignatelli** [comment]
MachineLearning_Engine/Compute/ClimateCharts/Rose.py 
```
import matplotlib as mpl
matplotlib.use("agg")
```
:)

**Comment by epignatelli** [comment]
Hey @tg359 do you know what's the status of https://github.com/BHoM/MachineLearning_Toolkit/tree/MachineLearning_Toolkit-%2341-AddPlotRose?

Are you blocked by something/someone else?

**Comment by tg359** [comment]
Closed as plot methods now handled in alternative toolkits.
