### ISSUE TITLE
MachinelLearning_Toolkit: Is there a linear regression function in the toolkit?

### ISSUE THREAD

**Issue by BingWangUS** [BHoM/MachineLearning_Toolkit#5]
Just wondering if there is such a function existing. If not, can we have one?

**Comment by epignatelli** [comment]
Hey @BingWangUS ! I just pull requested one, can you take a look and see if that's what you wanted?

**Comment by BingWangUS** [comment]
Hi @epignatelli , thanks for getting this really quick. I have some compiling issue with the PR, will review once I figure that out.
