### ISSUE TITLE
MachineLearning_Toolkit: Optional arguments for structured methods

### ISSUE THREAD

**Issue by BingWangUS** [BHoM/MachineLearning_Toolkit#54]
#### Description:

The structured methods are the regression models that can take variables. These variables all have default value but for some complicated model, tweaking the values is critical for for the regression task. These variables are also different for each model. Instead of mapping each variable out, I suggest adding an optional string input, for advance user to change variable value if needed. 

A prototype can be found here (https://github.com/BHoM/MachineLearning_Toolkit/tree/MachineLearning%2352-PrototypeArguments)

**Comment by BingWangUS** [comment]
@KentonPhillips-BH here is the issue if we want to expand regression models

**Comment by jamesramsden-bh** [comment]
Closed as related functionality has now been removed from this toolkit.
