### ISSUE TITLE
 MachineLearning_Toolkit: Vision.FindContours fails

### ISSUE THREAD

**Issue by BingWangUS** [BHoM/MachineLearning_Toolkit#55]
#### Description:

Error: Unable to cast object of type 'System.Collections.Generic.List1[System.Object]' to type 'System.Collections.Generic.List1[System.Collections.Generic.List`1[System.Double]]'.

**Comment by jamesramsden-bh** [comment]
Please provide more information to reproduce the error. What inputs did you provide? Providing a GH script with internalised data would be useful.

**Comment by jamesramsden-bh** [comment]
Disregard previous comment. Closed as related functionality has now been removed from this toolkit.
