### ISSUE TITLE
MachineLearning_Toolkit: Description of inputs and output

### ISSUE THREAD

**Issue by BingWangUS** [BHoM/MachineLearning_Toolkit#57]
#### What is missing/incorrect?

Some compute methods are missing descriptions of input and outputs:
- SupportVectorRegression.cs
- Vision.DetectObjects
- Vision.DrawDetection
- Vision.FindContours
- Vision.SemanticSegmentation
- Text.Answer
- Text.SentimentAnalysis
- Text.Summarise
- Audio.PlayAudio
- Audio.RecogniseSpeech
- Audio.SynthesiseSpeech

Some structured methods have the wrong description of input and outputs:
- LogisticRegression.cs
- LogisticRegression.py (comment in code are not correct)
- SupportVectorRegression.py (comment n code are not correct)

**Comment by jamesramsden-bh** [comment]
Closed as related functionality has now been removed from this toolkit.
