### ISSUE TITLE
Issue with MachineLearning.Query.Error

### ISSUE THREAD

**Issue by KentonPhillips-BH** [BHoM/MachineLearning_Toolkit#65]
#### Description:
The error component which computes the R^2 value does not appear to work.

#### Screenshot of Error

![image](https://user-images.githubusercontent.com/57185336/101419595-5707c200-38be-11eb-9659-3e043d97fcc7.png)

@BingWangUS

**Comment by BingWangUS** [comment]
This is a bug brought by the recent change for lazy import. It should be an easy fix with changing the namespace of the method from BH.Engine.MachineLearning to BH.Engine.MachineLearning.Structured
