### ISSUE TITLE
MachineLearning_Toolkit: Installation issue

### ISSUE THREAD

**Issue by BingWangUS** [BHoM/MachineLearning_Toolkit#88]
#### Description:

Recently ran into issue when trying to install machine learning toolkit on a new laptop. See the screenshot below

![image](https://user-images.githubusercontent.com/10835375/117891151-6a132980-b284-11eb-9483-ded74b359dbe.png)

Investigation needed to further identify where the problem are.

**Comment by jamesramsden-bh** [comment]
Closing as:
- Installation component has been updated
- Unable to reproduce on current beta's installation component. 

Please raise a new issue with full step by step for replication if this continues to be a problem.
